title: TheDisrupt.co
logo: /assets/img/logo.png
description: TheDisrupt is the first decentralized media organization founded in late 2018, to expose censored and restricted material that can disrupt our lives. We don't accept sponsorships or payments. We can only be contacted while using Tor. 
theme: jekyll-theme-minimal
