title: TheDisrupt.co
logo: /assets/img/logo.png
description: TheDisrupt is the first decentralized media organization founded in late 2018 to exposed censored and restricted material that can disrupt our lives. 
theme: jekyll-theme-minimal
